import pandas as pd
import matplotlib.pyplot as plt

# Code mostly generated by Google Gemini

def analyze_seismic_data(csv_file):
    # 1. Load data and parse the 'time' column into datetime objects
    df = pd.read_csv(csv_file)
    df['time'] = pd.to_datetime(df['time'])
    
    # 2. Extract the year for grouping
    df['year'] = df['time'].dt.year
    
    # --- Filter: Remove 2026 data to avoid incomplete year bias ---
    df = df[df['year'] < 2026]
    
    # 3. Define magnitude thresholds
    thresholds = {
        "Magnitude 2.5+ (Detectable)": 2.5,
        "Magnitude 4.0+ (Moderate)": 4.0,
        "Magnitude 5.0+ (Intense)": 5.0
    }
    
    # 4. Set up the plotting environment (sharex=False to show labels on every axis)
    fig, axes = plt.subplots(3, 1, figsize=(10, 15), sharex=False)
    plt.subplots_adjust(hspace=0.4) # Increased spacing slightly for labels
    
    colors = ['#3498db', '#e67e22', '#c0392b'] # Blue, Orange, Red
    
    # 5. Generate counts and plots
    for i, (label, val) in enumerate(thresholds.items()):
        # Filter the dataframe for magnitude
        filtered_df = df[df['mag'] >= val]
        
        # Count events per year
        yearly_counts = filtered_df.groupby('year').size()
        
        # Ensure all years are represented based on the filtered dataset
        if not df.empty:
            all_years = range(df['year'].min(), df['year'].max() + 1)
            yearly_counts = yearly_counts.reindex(all_years, fill_value=0)
            
            # Plotting
            axes[i].bar(yearly_counts.index, yearly_counts.values, color=colors[i])
            axes[i].set_title(label, fontsize=14, fontweight='bold')
            axes[i].set_ylabel("Number of Events")
            axes[i].set_xlabel("Year") # Now explicitly set for every subplot
            axes[i].grid(axis='y', linestyle='--', alpha=0.7)
            
            # Add value labels on top of bars
            if not yearly_counts.empty:
                max_val = max(yearly_counts)
                # Avoid zero division if max_val is 0
                label_offset = max_val * 0.01 if max_val > 0 else 0.1
                for year, count in yearly_counts.items():
                    if count > 0:
                        axes[i].text(year, count + label_offset, str(count), 
                                     ha='center', fontsize=9)

    plt.suptitle(f"Permian Basin Earthquake Activity", fontsize=16)
    
    # Show plot
    plt.show()

# Replace with your actual filename
analyze_seismic_data('query.csv')